### ISSUE TITLE
Do you welcome PR?

### ISSUE THREAD

**Issue by wucherpfennig** [mojiro/OneExperienceKB#1]
Are you still working on the theme? If you would like I could contribute some smaller fixes in order the clean up the otherwise great work.

BR wucherpfennig

**Comment by mojiro** [comment]
Hello @wucherpfennig,

I have stopped working on this theme, but feel free to place a PR and I will review it.

**Comment by wucherpfennig** [comment]
Do you use another one?

**Comment by mojiro** [comment]
I use this theme, but I am just satisfied at the moment of how it looks.

That's why I stopped updating it. It felt complete.

**Comment by wucherpfennig** [comment]
👍🏻 

Before I will try to make real PR. Please tell me what you think about the suggested changes (done via custom css);

```css
/* global */
#form-application_stylesheet{
min-height: 800px;
}

/* header */
header .logo a img{
filter: brightness(0) invert(1);
}

/* project view */

.coverimage img{
width: 100%;
height: auto;
}

#board th.board-column-header{
min-width:320px;
}

#board th.board-column-header .board-add-icon a{
display:inline-block;
height: auto;
margin: 0; 
padding:0;
}

#board th.board-column-header .board-column-title .dropdown-menu{
display: inline;
margin: 0 0.125rem;
}

#board tr > th a .fa{
margin:0 !important;
}

#board th.board-column-header .board-column-header-task-count{
margin-left: 0.25rem;
}

.project-header .filter-box-component .input-addon{
min-width: 45%;
}

.board-task-list-limit {
    background-color: var(--board-task-limit-color) !important;
    padding: 1rem !important;
}

/* task view */

.public-task{
max-width:1200px;
padding: 0 5rem;
margin: 2rem auto;
}

body #modal-box{
width:85% !important;
}

body #modal-box span.select2-container{
width:100% !important;
}

.task-links-table .column-10,
.subtasks-table .column-10{
width:15%;
}

.task-links-table .column-30,
.subtasks-table .column-30{
width:25%;
}

.select2-container--default .select2-selection--multiple .select2-selection__choice{
list-style-type: none;
padding: 0.125rem 0.25rem 0;
}

.select2-container .select2-search--inline{
list-style-type: none;
}

/* sidebar */
.sidebar i.fa.fa-file-pdf-o.fa-fw{
display:none;
}

/* notifications */
.web-notification-icon{
color:var(--link-color-primary) !important;
animation: bell 1s 1s both infinite;
}

@keyframes bell {
  0% { transform: rotate(0);  }
  10% { transform: rotate(30deg); }
  20% { transform: rotate(0); }
  80% { transform: rotate(0); }
  90% { transform: rotate(-30deg); }
  100% { transform: rotate(0); }
}
```

**Comment by mojiro** [comment]
Some additions and fixes are interesting, however I was unable to locate several classes that you are using.
ex. #form-application_stylesheet, .coverimage, .web-notification-icon

Would you like to proceed with a PR?

It would be really helpful to add some notes, explaining why you want to change some of the things.

In case you are using some other plugins and the changes are related to those, please mention which are they.

**Comment by wucherpfennig** [comment]
Dear, I annotated my suggestions. I will currently leave it as is as (and continue to work on it) but I do not have spare time to go through the projects css in order to properly merge the changes:

```css
/* global */

/* global - better css input field in settings */

#form-application_stylesheet{
min-height: 800px;
}

body #modal-box{
width:85% !important;
}

body #modal-box span.select2-container{
width:100% !important;
}

.task-links-table .column-10,
.subtasks-table .column-10{
width:15%;
}

.task-links-table .column-30,
.subtasks-table .column-30{
width:25%;
}

.select2-container--default .select2-selection--multiple .select2-selection__choice{
list-style-type: none;
padding: 0.125rem 0.25rem 0;
}

.select2-container .select2-search--inline{
list-style-type: none;
}

/* header */

/* header - make logo white */
header .logo a img{
filter: brightness(0) invert(1);
}

/* forms */

/* forms - better text box */
input[type="text"]:not(.input-addon-field){
width: 95%;
}

/* dashboard */

/* dashboard - better space usage for tags */
#dashboard .table-list > .table-list-row > .table-list-details span.table-list-category{
display: inline-block;
line-height: 0.85rem;
padding: 0.125rem;
width: auto;
margin-bottom: 0.25rem;
}

/* project view */

/* project view - plugin cover image, make images occupy 100% of task width */
.coverimage img{
width: 100%;
height: auto;
}

/* project view - wider columns */

#board th.board-column-header{
min-width:320px;
}

#board th.board-column-header-collapsed{
min-width: 32px;
}

/* project view - nice column headers */

#board th.board-column-header .board-add-icon a{
display:inline-block;
height: auto;
margin: 0; 
padding:0;
}

#board th.board-column-header .board-column-title .dropdown-menu{
display: inline;
margin: 0 0.125rem;
}

#board tr > th a .fa{
margin:0 !important;
}

#board th.board-column-header .board-column-header-task-count{
margin-left: 0.25rem;
}

.project-header .filter-box-component .input-addon{
min-width: 45%;
}

.board-task-list-limit {
background-color: var(--board-task-limit-color) !important;
padding: 1rem !important;
}

/* task view */

/* task view - fix for better public task display */

.public-task{
max-width:1200px;
padding: 0 5rem;
margin: 2rem auto;
}

/* sidebar */
#task-view .sidebar i.fa.fa-file-pdf-o.fa-fw{
display:none;
}

/* sidebar - better display of actions (including multiline + icons) */
#task-view .sidebar > ul li {
height: auto;
}

#task-view .sidebar > ul li a{
line-height: 2rem;
height:auto;
display:block;
padding: 0 20px 0 40px;
}

#task-view .sidebar li > a > .fa {
margin-left: -25px;
margin-right: 5px;
padding-right: 0px;
}

/* notifications */

/* notifications - make icon ring */

.web-notification-icon{
color:var(--link-color-primary) !important;
animation: bell 1s 1s both infinite;
}

@keyframes bell {
  0% { transform: rotate(0);  }
  10% { transform: rotate(30deg); }
  20% { transform: rotate(0); }
  80% { transform: rotate(0); }
  90% { transform: rotate(-30deg); }
  100% { transform: rotate(0); }
}
```
